package sui

// Modules
const (
	MODULE_MANAGE            string = "manage"
	MODULE_RECORD            string = "record"
	MODULE_CHILD             string = "child"
	MODULE_STAFF             string = "staff"
	MODULE_DONOR             string = "donor"
	MODULE_POOL              string = "pool"
	MODULE_GIFT              string = "gift"
	MODULE_NEED              string = "need"
	MODULE_TASK              string = "task"
	MODULE_CAMPAIGN          string = "campaign"
	MODULE_BACKGROUND_REFUND string = "background_refund"
)

// Functions
const (
	DONATE_SUI_POOL_FUNCTION                                         string = "donate_to_sui_pool"
	WITHDRAW_FROM_SUI_POOL_FUNCTION                                  string = "withdraw_from_sui_pool"
	ADD_CHILD_FUNCTION                                               string = "add_child"
	ADD_STRING_METADATA_FUNCTION                                     string = "add_string_metadata"
	ADD_NUMBER_METADATA_FUNCTION                                     string = "add_u64_metadata"
	UPDATE_STRING_METADATA_FUNCTION                                  string = "update_string_metadata"
	UPDATE_NUMBER_METADATA_FUNCTION                                  string = "update_u64_metadata"
	SUPPORT_CHILD_BOOKS_NEED_FUNCTION                                string = "support_child_books_need"
	SUPPORT_CHILD_BOOKS_NEED_FUNCTION_V2                             string = "support_child_books_need_v2"
	SUPPORT_CHILD_MEAL_NEED_FUNCTION                                 string = "support_child_meal_need"
	SUPPORT_CHILD_MEAL_NEED_FUNCTION_V2                              string = "support_child_meal_need_v2"
	SUPPORT_CHILD_SPECIAL_NEED_CAMPAIGN_FUNCTION                     string = "support_child_special_need_campaign"
	SUPPORT_CHILD_SPECIAL_NEED_CAMPAIGN_FUNCTION_V2                  string = "support_child_special_need_campaign_v2"
	SUPPORT_CHILD_HEALTH_INSURANCE_NEED_FUNCTION                     string = "support_child_health_insurance_need"
	SUPPORT_CHILD_HEALTH_INSURANCE_NEED_FUNCTION_V2                  string = "support_child_health_insurance_need_v2"
	CONFIRM_PROVIDE_MEAL_FOR_CHILD_FUNCTION                          string = "confirm_provide_meal_for_child"
	CREATE_CHILD_SPECIAL_NEED_PROPOSAL_FUNCTION                      string = "create_child_special_need_proposal"
	CONFIRM_CHILD_SPECIAL_NEED_PROPOSAL_FUNCTION                     string = "confirm_child_special_need_proposal"
	CREATE_SPECIAL_NEED_WITHDRAW_PROPOSAL_FUNCTION                   string = "create_child_special_need_withdraw_proposal"
	CREATE_CHILD_BOOKS_NEED_WITHDRAW_PROPOSAL_FUNCTION               string = "create_child_books_need_withdraw_proposal"
	CREATE_CHILD_MEAL_NEED_WITHDRAW_PROPOSAL_FUNCTION                string = "create_child_meal_need_withdraw_proposal"
	CREATE_CHILD_SPEICAL_NEED_WITHDRAW_PROPOSAL_FUNCTION             string = "create_special_need_withdraw_proposal"
	CREATE_CHILD_BOOKS_NEED_WITHDRAW_PROPOSAL_FUNCTION_V2            string = "create_child_books_need_withdraw_proposal_v2"
	CREATE_CHILD_HEALTH_INSURANCE_NEED_WITHDRAW_PROPOSAL_FUNCTION    string = "create_child_health_insurance_need_withdraw_proposal"
	CREATE_CHILD_HEALTH_INSURANCE_NEED_WITHDRAW_PROPOSAL_FUNCTION_V2 string = "create_child_health_insurance_need_withdraw_proposal_v2"
	CREATE_CHILD_MEAL_NEED_WITHDRAW_PROPOSAL_FUNCTION_V2             string = "create_child_meal_need_withdraw_proposal_v2"
	CREATE_CHILD_SPEICAL_NEED_WITHDRAW_PROPOSAL_FUNCTION_V2          string = "create_special_need_withdraw_proposal_v2"
	CREATE_CHILD_SPECIAL_NEED_PROPOSAL_FUNCTION_V2                   string = "create_child_special_need_proposal_v2"
	WITHDRAW_FROM_SPECIAL_NEED_CAMPAIGN_FUNCTION                     string = "withdraw_from_special_need_campaign"
	WITHDRAW_FROM_SPECIAL_NEED_CAMPAIGN_FUNCTION_v2                  string = "withdraw_from_special_need_campaign_v2"
	WITHDRAW_FROM_BOOKS_NEED_PROPOSAL_FUNCTION                       string = "withdraw_from_books_need_proposal"
	WITHDRAW_FROM_BOOKS_NEED_PROPOSAL_FUNCTION_V2                    string = "withdraw_from_books_need_proposal_v2"
	WITHDRAW_FROM_HEALTH_INSURANCE_NEED_PROPOSAL_FUNCTION            string = "withdraw_from_health_insurance_need_proposal"
	WITHDRAW_FROM_HEALTH_INSURANCE_NEED_PROPOSAL_FUNCTION_V2         string = "withdraw_from_health_insurance_need_proposal_v2"
	WITHDRAW_FROM_MEAL_NEED_PROPOSAL_FUNCTION                        string = "withdraw_from_meal_need_proposal"
	WITHDRAW_FROM_MEAL_NEED_PROPOSAL_FUNCTION_V2                     string = "withdraw_from_meal_need_proposal_v2"
	CONFIRM_PROVIDE_MEAL_FOR_CHILD_FUNCTION_V2                       string = "confirm_provide_meal_for_child_v2"
	CONFIRM_PROVIDE_BOOKS_FOR_CHILD_FUNCTION_V2                      string = "confirm_provide_books_for_child_v2"
	CONFIRM_PROVIDE_HEALTH_INSURANCE_FOR_CHILD_FUNCTION_V2           string = "confirm_provide_health_insurance_for_child_v2"
	SUBMIT_TASK_FUNCTION                                             string = "submit_task"
	VOTE_SPECIAL_NEED_PROPOSAL_FUNCTION                              string = "vote_special_need_proposal"
	EDIT_SPECIAL_NEED_DAO_RATE_FUNCTION                              string = "edit_special_need_dao_rate"
	EDIT_WITHDRAW_DAO_RATE_FUNCTION                                  string = "edit_withdraw_dao_rate"
	REGISTER_STAFF_FUNCTION                                          string = "register_staff"
	REGISTER_VOLUNTEER_FUNCTION                                      string = "register_volunteer"
	REGISTER_LOCAL_LEADER_FUNCTION                                   string = "register_local_leader"
	REGISTER_ADMIN_FUNCTION                                          string = "register_admin"
	DONATE_TO_POOL_FUNCTION                                          string = "donate_to_pool"
	DONATE_TO_POOL_FUNCTION_V2                                       string = "donate_to_pool_v2"
	DONATE_TO_LOCAL_POOL_FUNCTION                                    string = "donate_to_local_pool"
	DONATE_TO_LOCAL_POOL_FUNCTION_V2                                 string = "donate_to_local_pool_v2"
	WITHDRAW_FROM_POOL_FUNCTION                                      string = "withdraw_from_pool"
	CREATE_WITHDRAW_PROPOSAL_FUNCTION                                string = "create_withdraw_proposal"
	CREATE_WITHDRAW_PROPOSAL_V2_FUNCTION                             string = "create_withdraw_proposal_v2"
	VOTE_WITHDRAW_PROPOSAL_FUNCTION                                  string = "vote_withdraw_proposal"
	VOTE_POOL_CAMPAIGN_WITHDRAW_PROPOSAL_FUNCTION                    string = "vote_pool_campaign_withdraw_proposal"
	VOTE_BOOKS_NEED_WITHDRAW_PROPOSAL_FUNCTION                       string = "vote_books_need_withdraw_proposal"
	VOTE_MEAL_NEED_WITHDRAW_PROPOSAL_FUNCTION                        string = "vote_meal_need_withdraw_proposal"
	VOTE_HEALTH_INSURANCE_NEED_WITHDRAW_PROPOSAL_FUNCTION            string = "vote_health_isurance_need_withdraw_proposal"
	VOTE_SPECIAL_NEED_CAMPAIGN_WITHDRAW_PROPOSAL_FUNCTION            string = "vote_special_need_campaign_withdraw_proposal"
	UPDATE_PUBLISHER_NFT_FUNCTION                                    string = "update_publisher_nft"
	CREATE_CENTER_FUNCTION                                           string = "create_children_center"
	UPLOAD_CENTER_IMAGE_FUNCTION                                     string = "upload_center_image"
	UPLOAD_CENTER_ADDRESS_FUNCTION                                   string = "upload_center_address"
	UPLOAD_CENTER_PHONE_NUMBER_FUNCTION                              string = "upload_center_phone_number"
	MINT_REGISTER_VOLUNTEER_CAP_FUNCTION                             string = "mint_register_volunteer_cap"
	MINT_REGISTER_LEADER_CAP_FUNCTION                                string = "mint_register_local_leader_cap"
	MINT_REGISTER_ADMIN_CAP_FUNCTION                                 string = "mint_register_admin_cap"
	MINT_UPLOAD_CENTER_CAP_FUNCTION                                  string = "mint_upload_center_cap"
	CREATE_GIFT_FOR_CHILD_FUNCTION                                   string = "create_gift_for_child"
	CREATE_GIFT_FOR_CENTER_FUNCTION                                  string = "create_gift_for_center"
	CONFIRM_RECIEVE_CHILD_GIFT_FUNCTION                              string = "confirm_recieved_child_gift"
	CONFIRM_RECIEVE_CENTER_GIFT_FUNCTION                             string = "confirm_recieved_center_gift"
	CANCEL_GIFT_FUNCTION                                             string = "cancel_gift"
	UPDATE_CHILD_BOOKS_NEED_FUNCTION                                 string = "update_child_books_need"
	UPDATE_CHILD_MEAL_NEED_FUNCTION                                  string = "update_child_meal_need"
	UPDATE_CHILD_HEALTH_INSURANCE_NEED_FUNCTION                      string = "update_child_health_insurance_need"
	EDIT_UPDATE_BOOKS_NEED_DATES_FUNCTION                            string = "edit_update_books_need_dates"
	EDIT_UPDATE_MEAL_NEED_DATES_FUNCTION                             string = "edit_update_meal_need_dates"
	EDIT_UPDATE_HEALTH_INSURANCE_NEED_DATES_FUNCTION                 string = "edit_update_health_insurance_need_dates"
	CREATE_CAMPAIGN_FOR_MAIN_POOL_FUNCTION                           string = "create_campaign_for_main_pool"
	CREATE_CAMPAIGN_FOR_REGION_POOL_FUNCTION                         string = "create_campaign_for_region_pool"
	SUPPORT_CAMPAIGN_FUNCTION                                        string = "support_campaign"
	SUPPORT_CAMPAIGN_FUNCTION_v2                                     string = "support_campaign_v2"
	CREATE_CAMPAIGN_WITHDRAW_PROPOSAL_FUNCTION                       string = "create_campaign_withdraw_proposal"
	WITHDRAW_FROM_CAMPAIGN_FUNCTION                                  string = "withdraw_from_campaign"
	WITHDRAW_FROM_CAMPAIGN_FUNCTION_V2                               string = "withdraw_from_campaign_v2"
	REFUND_POOL_VOTE_POWER_FUNCTION                                  string = "refund_pool_vote_power_to_approvers"
	ADMIN_REFUND_POOL_VOTE_POWER_FUNCTION                            string = "admin_refund_pool_vote_power_to_approvers"
	REFUND_POOL_CAMPAIGN_VOTE_POWER_FUNCTION                         string = "refund_pool_campaign_vote_power_to_approvers"
	ADMIN_REFUND_POOL_CAMPAIGN_VOTE_POWER_FUNCTION                   string = "admin_refund_pool_campaign_vote_power_to_approvers"
	REFUND_CHILD_SPECIAL_NEED_CAMPAIGN_VOTE_POWER_FUNCTION           string = "refund_child_special_need_campaign_vote_power_to_approvers"
	ADMIN_REFUND_CHILD_SPECIAL_NEED_CAMPAIGN_VOTE_POWER_FUNCTION     string = "admin_refund_child_special_need_campaign_vote_power_to_approvers"
	REFUND_CHILD_MEAL_NEED_VOTE_POWER_FUNCTION                       string = "refund_child_meal_meed_vote_power_to_approvers"
	ADMIN_REFUND_CHILD_MEAL_NEED_VOTE_POWER_FUNCTION                 string = "admin_refund_child_meal_meed_vote_power_to_approvers"
	REFUND_CHILD_BOOKS_NEED_VOTE_POWER_FUNCTION                      string = "refund_child_books_need_vote_power_to_approvers"
	ADMIN_REFUND_CHILD_BOOKS_NEED_VOTE_POWER_FUNCTION                string = "admin_refund_child_books_need_vote_power_to_approvers"
	REFUND_CHILD_HEALTH_INSURANCE_NEED_VOTE_POWER_FUNCTION           string = "refund_child_health_insurance_need_vote_power_to_approvers"
	ADMIN_REFUND_CHILD_HEALTH_INSURANCE_NEED_VOTE_POWER_FUNCTION     string = "admin_refund_child_health_insurance_need_vote_power_to_approvers"
)

// Structs
const (
	MANAGE_STRUCT                string = "Manage"
	TRANSACTION_RECORD_STRUCT    string = "TransactionRecord"
	CHILD_STRUCT                 string = "Child"
	ADMIN_NFT_STRUCT             string = "AdminNFT"
	STAFF_NFT_STRUCT             string = "StaffNFT"
	DONOR_NFT_STRUCT             string = "DonorNFT"
	WITHDRAW_PROPOSAL_STRUCT     string = "WithDrawProposal"
	BOOKS_NEED_STRUCT            string = "BooksNeed"
	MEAL_NEED_STRUCT             string = "MealNeed"
	SPECIAL_NEED_PROPOSAL_STRUCT string = "SpecialNeedProposal"
	SPECIAL_NEED_CAMPAIGN_STRUCT string = "SpecialNeedCampaign"
	GIFT_STRUCT                  string = "Gift"
	CAMPAIGN_STRUCT              string = "Campaign"
)

// Cap structs
const (
	ADMIN_CAP_STRUCT              string = "AdminCap"
	UPDATE_ADMIN_INFO_CAP_STRUCT  string = "UpdateAdminInfoAfterPublishCap"
	REGISTER_VOLUNTEER_CAP_STRUCT string = "RegisterVolunteerCap"
	REGISTER_LEADER_CAP_STRUCT    string = "RegisterLocalLeaderCap"
	REGISTER_ADMIN_CAP_STRUCT     string = "RegisterAdminCap"
	UPLOAD_CENTER_CAP_STRUCT      string = "UploadCenterCap"
)

// DAO structs
const (
	SPECIAL_NEED_DAO_STRUCT string = "SpecialNeedDao"
	WITHDRAW_DAO_STRUCT     string = "PoolWithdrawDao"
)

// Events
const (
	TRANSACTION_RECORD_EVENT string = "TransactionRecordEvent"
	WITHDRAW_PROPOSAL_EVENT  string = "WithdrawProposalCreated"
)
