package shared

const (
	AGROTRUST_REGION   string = "AgroTrust"
	TUYEN_QUANG_REGION string = "Tỉnh Tuyên Quang"
	LAO_CAI_REGION     string = "Tỉnh Lào Cai"
	THAI_NGUYEN_REGION string = "Tỉnh Thái Nguyên"
	PHU_THO_REGION     string = "Tỉnh Phú Thọ"
	BAC_BINH_REGION    string = "Tỉnh Bắc Ninh"
	HUNG_YEN_REGION    string = "Tỉnh Hưng Yên"
	HAI_PHONG_REGION   string = "Thành phố Hải Phòng"
	NINH_BINH_REGION   string = "Tỉnh Ninh Bình"
	QUANG_TRI_REGION   string = "Tỉnh Quảng Trị"
	DA_NANG_REGION     string = "Thành phố Đà Nẵng"
	QUANG_NGAI_REGION  string = "Tỉnh Quảng Ngãi"
	GIA_LAI_REGION     string = "Tỉnh Gia Lai"
	KHANH_HOA_REGION   string = "Tỉnh Khánh Hoà"
	LAM_DONG_REGION    string = "Tỉnh Lâm Đồng"
	DAK_LAK_REGION     string = "Tỉnh Đắk Lắk"
	HO_CHI_MINH_REGION string = "Thành phố Hồ Chí Minh"
	DONG_NAI_REGION    string = "Tỉnh Đồng Nai"
	TAY_NINH_REGION    string = "Tỉnh Tây Ninh"
	CAN_THO_REGION     string = "Thành phố Cần Thơ"
	VINH_LONG_REGION   string = "Tỉnh Vĩnh Long"
	DONG_THAP_REGION   string = "Tỉnh Đồng Tháp"
	CA_MAU_REGION      string = "Tỉnh Cà Mau"
	AN_GIANG_REGION    string = "Tỉnh An Giang"
	HA_NOI_REGION      string = "Thành phố Hà Nội"
	HUE_REGION         string = "Thành phố Huế"
	LAI_CHAU_REGION    string = "Tỉnh Lai Châu"
	DIEN_BIEN_REGION   string = "Tỉnh Điện Biên"
	SON_LA_REGION      string = "Tỉnh Sơn La"
	LANG_SON_REGION    string = "Tỉnh Lạng Sơn"
	QUANG_NINH_REGION  string = "Tỉnh Quảng Ninh"
	THANH_HOA_REGION   string = "Tỉnh Thanh Hoá"
	NGHE_AN_REGION     string = "Tỉnh Nghệ An"
	HA_TINH_REGION     string = "Tỉnh Hà Tĩnh"
	CAO_BANG_REGION    string = "Tỉnh Cao Bằng"
)
