package shared

const (
	USER_REPOSITORY                                 string = "User Repository"
	USER_SECURITY_REPOSITORY                        string = "User Security Repository"
	PAYMENT_REPOSITORY                              string = "Payment Repository"
	BANK_PROFILE_REPOSITORY                         string = "Bank Profile Repository"
	PROFILE_REPOSITORY                              string = "Profile Repository"
	REGISTRATION_REQUEST_REPOSITORY                 string = "Registration Request Repository"
	CENTER_REQUEST_REPOSITORY                       string = "Center Request Repository"
	ADMIN_REQUEST_REPOSITORY                        string = "Admin Request Repository"
	LEADER_REQUEST_REPOSITORY                       string = "Leader Request Repository"
	VOLUNTEER_REQUEST_REPOSITORY                    string = "Volunteer Request Repository"
	UPLOAD_CHILD_REQUEST_REPOSITORY                 string = "Upload Child Request Repository"
	OFFCHAIN_DONATION_REPOSITORY                    string = "Off-Chain Donation Repository"
	OFFCHAIN_WITHDRAW_PROPOSAL_REPOSITORY           string = "Off-Chain Withdraw Proposal Repository"
	VOLUNTEER_NOTI_REPOSITORY                       string = "Volunteer Noti Repository"
	LEADER_NOTI_REPOSITORY                          string = "Leader Noti Repository"
	SUPPORTED_REGION_PROPOSAL                       string = "Supported Region Suggestion Repository"
	PENDING_WITHDRAW_PROPOSAL_REPOSITORY            string = "Pending Withdraw Proposal Repository"
	MEAL_SUPPORT_DURATION_REPOSITORY                string = "Meal Support Duration Repository"
	TASK_REPOSITORY                                 string = "Task Repository"
	TASK_PROOF_REPOSITORY                           string = "Task Proof Repository"
	CHILD_TASK_DETAIL_REPOSITORY                    string = "Child Task Detail Repository"
	PENDING_CHILD_SPECIAL_NEED_PROPOSAL_REPOSITORY  string = "Pending Child Special Need Proposal Repository"
	PENDING_CAMPAIGN_REPOSITORY                     string = "Pending Campaign Repository"
	BACKGROUND_CHILDREN_WITHDRAW_REQUEST_REPOSITORY string = "Background Children Withdraw Requests Repository"
	PLATFORM_CONFIG_REPOSITORY                      string = "Platform Config Repository"
	TX_REPOSITORY                                   string = "Transaction Repository"
)
